meta_product_name: "Noémie Piérart"
meta_title: "Noémie Pierart - Développeur web/mobile"
meta_description: "Le Wagon Fullstack Bootcam Alumni | Ruby on Rails, Javascript, HTML/CSS, PostgreSQL, etc. | Web applications | Web sites | Le Wagon"
meta_image: "og_banner.png" # should exist in `app/assets/images/`
twitter_account: "@NoemiePierart"   # required for Twitter Cards