meta_product_name: "Noémie Piérart"
meta_title: "Noémie Pierart - Développeur web/mobile"
meta_description: "Bootcamp fullstack du Wagon: Ruby on Rails, Javascript, HTML/CSS, PostgreSQL, etc."
meta_image: "og_banner.png" # should exist in `app/assets/images/`
twitter_account: "@NoemiePierart"   # required for Twitter Cards